global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000

  - job_name: "frontend"
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - frontend:3000
